sudo: false
language: java
script: mvn test package

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/

deploy:
  provider: releases
  api_key:
    secure: LnO4tOdUZXMTIkcnsOeskB9KDFt3Y+aesqhTlIE6P0Csn4mjJTi3jCgZDa09qyP9JHiXKovLpD6uoVf7BYublZ1nwayCrrRraTDuPZ7dTEL/D/lPezEpGz1gRsHN4B0QI1Cfgwm8f34xd2k77GNCm2Y9vlu8LpkildZJ6clp4gw=
  file: /home/travis/build/bigspotteddog/number-translator/target/number-translator-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
    repo: bigspotteddog/number-translator
    all_branches: true